### ISSUE TITLE
Error when Dict keys include string with slash

### ISSUE THREAD

**Issue by CorySimon** [JuliaIO/JLD.jl#108]
using JLD
    foo = Dict("mmol/g" => 23.0)
    save("blah.jld", foo)
    bar = load("blah.jld")

The result is:

    Dict{String,Any} with 1 entry:
    "mmol" => Dict{String,Any}(Pair{String,Any}("g",23.0))

**Comment by simonster** [comment]
`save(filename, dict)` creates datasets corresponding to the dict keys. You are saving a scalar dataset named `g` containing `23.0` inside a group `mmol`. If you want to save the dict as a dataset named `foo`, use `save("blah.jld", "foo", foo)` and `load("blah.jld", "foo")`.
