### ISSUE TITLE
`@load` loads only variable names, not values

### ISSUE THREAD

**Issue by dpsanders** [JuliaIO/JLD.jl#115]
```
julia> using JLD

julia> a, b = 3, 4.5;

julia> @save "vars.jld"

julia> @load "vars.jld"
3-element Array{Symbol,1}:
 :a
 :ans
 :b
```

**Comment by simonster** [comment]
`@load` loads all variables present in the file into the global scope and returns an array of symbols corresponding to the variables loaded. If you call `@load "vars.jld"` in a new session in an empty workspace, it will define `a`, `b`, and `ans`. If you are instead looking for a Dict that contains the values, use `load("vars.jld")`.

**Comment by dpsanders** [comment]
Thankd and apologies.
