### ISSUE TITLE
How to read range of jld file ?

### ISSUE THREAD

**Issue by programistawpf** [JuliaIO/JLD.jl#119]
How to read range of jld file ?
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using JLD

julia> D=rand(10,10)
10x10 Array{Float64,2}:
 0.0870527  0.436815    0.215768  0.374257  0.477098  0.920663    0.0679468  0.893296  0.656644   ....
 0.687406   0.00995926  0.96358   0.846045  0.188301  0.722089    0.109776   0.86346   0.725332   0.36931

julia> save("D.jld","D",D)

julia> D=load("D.jld","D",(:,1))
ERROR: too few arguments
 in println at strings/io.jl:25

julia>
Paul

**Comment by timholy** [comment]
It's better to use https://discourse.julialang.org for this kind of question. I will comment that this is covered in the HDF5 docs (the `doc/` directory, not the README).
