### ISSUE TITLE
@save "foo.jld" doesn't save anything instead of saving everything inside a module

### ISSUE THREAD

**Issue by wupeifan** [JuliaIO/JLD.jl#139]
Julia 0.5, Windows 7, latest version of JLD,

@save "foo.jld"
d = load("foo.jld")
Dict String -> Any with 0 entries

When I use @save "foo.jld" a, it does save a.

**Comment by simonster** [comment]
In the code snippet above, you don't define any variables before you call `@save`, and so `@save` doesn't save any variables.

Also note that, if you do not specify any variable names, `@save` will save all global variables, but not any variables local to the current function.

**Comment by wupeifan** [comment]
For sure I have a bunch of variables before I call @save. I just didn't put '...' here. I am aware that I am not going to save an empty module.
And I want that to save all global variables inside a module. It is not inside a function. I call it globally under a module.

**Comment by simonster** [comment]
Can you provide some code that reproduces the issue?

**Comment by simonster** [comment]
Thanks, that's very useful. It seems that `@save` currently saves only exported variables from modules other than Main. Perhaps we should change this.

**Comment by wupeifan** [comment]
I see. Then that's the way I am using the function is not correct.
Since description of this function says "save the variables like Matlab saving workspace". I was thinking maybe saving inside module is similar.
