### ISSUE TITLE
isgeneric not defined when saving a function

### ISSUE THREAD

**Issue by cstjean** [JuliaIO/JLD.jl#171]
```julia
julia> using JLD

julia> JLD.save("tmp.jld", "id", identity)
ERROR: UndefVarError: isgeneric not defined
Stacktrace:
 [1] func2expr(::Function) at /Users/cedric/.julia/v0.6/JLD/src/JLD.jl:848
```

On [this line](https://github.com/JuliaIO/JLD.jl/blob/5022d9bbf16f7e379c2e5e86c13406b17cceb893/src/JLD.jl#L848). Error aside, wouldn't it be possible to save generic functions the same way Python does, by storing something like `(:Base, :identity)`?

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaIO/JLD.jl/issues/57

**Comment by augustvanhout** [comment]
This one worked for me! https://discourse.julialang.org/t/save-variable/33986
