### ISSUE TITLE
Memory mapping not working

### ISSUE THREAD

**Issue by ReubenHill** [JuliaIO/JLD.jl#174]
I'm trying to get memory mapping from JLD files working as outlined in [jld.md](https://github.com/JuliaIO/JLD.jl/blob/master/doc/jld.md). I am running Julia 0.6.0 on Windows 10 64 bit  (version 1703). 

When I run the following code, I get thrown an error.

Code:
```Julia
using JLD
let
  local v = rand(16, 20480*10)
  save("mmap.jld","v",v)
end
file = jldopen("mmap.jld", "r", mmaparrays=true)
v = read(file, "v")
```

Output:
```
could not create file mapping: The operation completed successfully. 
in read at JLD\src\JLD.jl:357
in read at JLD\src\JLD.jl:383
in read_array at JLD\src\JLD.jl:417
in read_array at JLD\src\JLD.jl:420
in read_vals at JLD\src\JLD.jl:429
in readmmap at HDF5\src\HDF5.jl:1496
in mmap at base\mmap.jl:102
in #mmap#1 at base\mmap.jl:133
```

Any thoughts?

**Comment by musm** [comment]
Memory mapping does not work on windows due to HDF5 issue  https://github.com/JuliaIO/HDF5.jl/issues/357
