### ISSUE TITLE
Deprecated Compat.ASCIIString & Compat.UTF8String

### ISSUE THREAD

**Issue by chbian** [JuliaIO/JLD.jl#179]
Compat deprecated ASCIIString and UTF8String when it dropped julia-0.4 support. Please consider replacing all instances of Compat.ASCIIString/Compat.UTF8String with String.

**Comment by ararslan** [comment]
Yep, we should definitely do that. Would you be willing to submit a PR for that, @bravesalmon?

**Comment by yuyichao** [comment]
I've also got local branches waiting for Compat.jl

**Comment by bravesalmon** [comment]
@ararslan, sure. working on it.

**Comment by Keno** [comment]
I might have something that can do this automatically, hold on.
