### ISSUE TITLE
JLD unable to load files from separate folders?

### ISSUE THREAD

**Issue by gaomrx** [JuliaIO/JLD.jl#201]
Not sure why I am unable to load files from separate folders. The code was working fine just last week. I am using JLD 0.8.3. 

![image](https://user-images.githubusercontent.com/6380557/34136838-ae024c6e-e435-11e7-8fe9-d678996cf29b.png)

**Comment by gaomrx** [comment]
jldopen does not work too.

![image](https://user-images.githubusercontent.com/6380557/34137110-188c12da-e437-11e7-99ba-0d7c152a7fa9.png)

**Comment by rdeits** [comment]
This doesn't look like a JLD issue. To open a file outside of the current working directory, you have to give it's *full* path, not just its name.

**Comment by gaomrx** [comment]
Thanks, passing in the full path works, but my original way of opening files with JLD was working too up until last week.

**Comment by timholy** [comment]
Are you sure? I can't think of any change that would explain that, and it would have been such weird (and frankly dangerous) behavior that I would have called it a bug.

**Comment by gaomrx** [comment]
@timholy Do you mean passing in the full path? 

I managed to find a even stranger example now where I can load a file outside pwd() starting from the second element but not the first.

![image](https://user-images.githubusercontent.com/6380557/34281705-77b135f2-e68e-11e7-9e15-0401b67c52d7.png)

**Comment by rdeits** [comment]
You have a file in the current directory with the same name as file you're trying to load outside the directory. That's the one that's being loaded.
