### ISSUE TITLE
Can't save NamedTuple

### ISSUE THREAD

**Issue by fredcallaway** [JuliaIO/JLD.jl#241]
`JLD.save("test.jld", "foo", (x=1, y=2))` fails with the error "ERROR: type parameters with objects of type Tuple{Symbol,Symbol} are currently unsupported"

Seeing as how prominent `NamedTuples` are, this seems like a pretty big missing feature. Would this be really hard to patch?

**Comment by Datseris** [comment]
bump

**Comment by astrorCoder** [comment]
Has it been fixed? I'm trying to do the same and I still get the same error.
