### ISSUE TITLE
Error using @save in Main

### ISSUE THREAD

**Issue by Thuener** [JuliaIO/JLD.jl#253]
```
using JLD
a = 1
@save "test.jld"
```
I get the erro:
`ERROR: LoadError: UndefVarError: current_module not defined`

Seems that there is some old 0.6 code here. I will submit a PR.

**Comment by Thuener** [comment]
I don't know how to create unit tests for this.

**Comment by ericagol** [comment]
I'm having the same error.

**Comment by aramirezreyes** [comment]
Bumping this. @simonster, could we have someone check out this Issue/PR?
