### ISSUE TITLE
Failed to clone JLD

### ISSUE THREAD

**Issue by nzarif** [JuliaIO/JLD.jl#264]
Hi,

I am really sorry if this issue has been mentioned before, I searched and could not find anything really similar. I have this problem:
I am trying to run a julia code that has "using JLD" but I get this error:

"ERROR: LoadError: ArgumentError: Package JLD not found in current path:
- Run `import Pkg; Pkg.add("JLD")` to install the JLD package."

So I opened julia's console and entered:

" import Pkg;
Pkg.add("JLD"); "

and I got this error:
"Cloning default registries into `C:\Users\niloofar\.julia`
Cloning registry from "https://github.com/JuliaRegistries/General.git"
ERROR: failed to clone from https://github.com/JuliaRegistries/General.git, error: GitError(Code:ECERTIFICATE, Class:Net, unknown certificate check failure)"

(it then prints out the whole stacktrace that I have not copied here)

how can I fix this?

**Comment by musm** [comment]
try again, we should've fixed these issues already
