### ISSUE TITLE
error on Julia 1.7.0-beta2

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaIO/JLD.jl#300]
```
using JLD
D = Dict("a"=>"Hazel")
save("test.jld","D",D)
```
gives 
```
error encountered while save FileIO.File{FileIO.DataFormat{:JLD}, String}("test.jld").              
                                                  
Fatal error:                                      
ERROR: LoadError: type DataType has no field mutable         
....```

**Comment by mauro3** [comment]
`T.mutable` needs to be replaced with `ismutabletype` now.  Similar to here https://github.com/mauro3/SimpleTraits.jl/pull/76/files

**Comment by nandoconde** [comment]
Has anyone taken action for this?

**Comment by mauro3** [comment]
Unlikely, as there is no pull request.  It looks like there is just one instance: https://github.com/JuliaIO/JLD.jl/blob/83ea0c5ef7293c78d7d9c8ffdf9ede599b54dc4c/src/jld_types.jl#L311, so it shouldn't be too hard (if that is indeed the only issue).  But I just opened a PR in Compat.jl, then I think it should just be a `using Compat`.

**Comment by nandoconde** [comment]
I was about to make a PR changing it manually. It is present in some other places

# `jld_types.jl`
https://github.com/JuliaIO/JLD.jl/blob/83ea0c5ef7293c78d7d9c8ffdf9ede599b54dc4c/src/jld_types.jl#L311
https://github.com/JuliaIO/JLD.jl/blob/83ea0c5ef7293c78d7d9c8ffdf9ede599b54dc4c/src/jld_types.jl#L314
https://github.com/JuliaIO/JLD.jl/blob/83ea0c5ef7293c78d7d9c8ffdf9ede599b54dc4c/src/jld_types.jl#L509
https://github.com/JuliaIO/JLD.jl/blob/83ea0c5ef7293c78d7d9c8ffdf9ede599b54dc4c/src/jld_types.jl#L516
https://github.com/JuliaIO/JLD.jl/blob/83ea0c5ef7293c78d7d9c8ffdf9ede599b54dc4c/src/jld_types.jl#L529
https://github.com/JuliaIO/JLD.jl/blob/83ea0c5ef7293c78d7d9c8ffdf9ede599b54dc4c/src/jld_types.jl#L539

# `JLD00.jl`
https://github.com/JuliaIO/JLD.jl/blob/83ea0c5ef7293c78d7d9c8ffdf9ede599b54dc4c/src/JLD00.jl#L475

# `JLD.jl`
https://github.com/JuliaIO/JLD.jl/blob/83ea0c5ef7293c78d7d9c8ffdf9ede599b54dc4c/src/JLD.jl#L461
https://github.com/JuliaIO/JLD.jl/blob/83ea0c5ef7293c78d7d9c8ffdf9ede599b54dc4c/src/JLD.jl#L471
https://github.com/JuliaIO/JLD.jl/blob/83ea0c5ef7293c78d7d9c8ffdf9ede599b54dc4c/src/JLD.jl#L696

Do you want to wait for Compat, or manually change it?

**Comment by mauro3** [comment]
I have nothing to say here... but my take is that if it is just this one thing, then I wouldn't necessarily add the Compat.jl dependency.

**Comment by musm** [comment]
Fixed in https://github.com/JuliaIO/JLD.jl/pull/303 courtesy @mkitti

**Comment by musm** [comment]
> I'm getting this error when loading a JLD in 1.7, wondering if it's related?

I've just made a new release with the latest fixes, please check now, should be fixed !
