### ISSUE TITLE
Warning:  object_info is deprecated, use API.h5o_get_info1 instead

### ISSUE THREAD

**Issue by roccminton** [JuliaIO/JLD.jl#324]
I'm saving and loading Dictionaries of type {:String,:Any}. My values are either integers, vectors or matricies. Both saving and loading work without further problems. I ony get the following warning everytime:

┌ Warning: `object_info(obj::Union{File, Object})` is deprecated, use `API.h5o_get_info1(checkvalid(obj))` instead.
│   caller = write_ref(parent::JLD.JldFile, data::Int64, wsession::JLD.JldWriteSession) at JLD.jl:696
└ @ JLD ~/.julia/packages/JLD/S6t6A/src/JLD.jl:696

Moreover I have the impression that loading and saving takes unnecessarily much time and that the saved files take unnecessarily much storage space. 

Can someone explain the warning to me? May there be a relation between my impression on time and storage consumption and that particular warning?

Thank you very much for any help!

**Comment by mkitti** [comment]
This is mainly a note to the developer to use a different API call. You can ignore it.

As far as performance issues, it would be good if you could provide a minimum working example for us to analyze.
