### ISSUE TITLE
Error when opening a jld file

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaIO/JLD.jl#55]
I have a variable `outfile` that reads a string "m1.jld" from a text file and I do `fid = jldopen(outfile, "w");` The following error message pops up 

```
ERROR: LoadError: SystemError: opening file m1.jld: No such file or directory. 
```

But on the other hand when I do `fid = jldopen("m1.jld", "w");` everything works fine. So I printed out the outfile and that is fine too. But in the folder (via terminal), a file has been created by the program under the name "m1.jld?". I even tried doing a `chomp` on the outfile to get rid of any breakline characters. Any help with this issue is appreciated.

**Comment by nalimilan** [comment]
Does it work if you manually assign the value `"m1.jld"` to `outfile`? Could you copy and paste the value of `outfile` here? The question mark at the end of `"m1.jld?"` could be the sign that an invalid character appears at the end of the string you read from the text file. In that case, it wouldn't be related at all to `jldopen`.

**Comment by kaarthiksundar** [comment]
Yes, it works now. I did a Pkg.update() and it works fine now. Closing the issue.

**Comment by kaarthiksundar** [comment]
Okay, I am running into the same issue again. It works when I do it manually. I use the following piece of code

    outfile = chomp(thisline[2]) # thisline[2] contains "m1.jld\n"
    file = "m1.jld"
    @asssert outfile == file
    fid = jldopen(outfile, "w");
    write(fid, "TotalTime", totalWorkTime);
    close(fid);

The file created in the folder is "m1.jld\n". If you notice I did do a chomp and have an assert statement.

**Comment by nalimilan** [comment]
Do you get the same result if you do `outfile = chomp("m1.jld\n")`? And if you do `open(outfile, "w")` instead of `jldopen`?

**Comment by kaarthiksundar** [comment]
If i do that, I don't have any issues.

**Comment by kaarthiksundar** [comment]
I don't get any errors if I do that, but when I try to load up the data using julia it says `ERROR: FileIO.File{FileIO.DataFormat{:UNKNOWN}}("m1.jld") couldn't be recognized by FileIO.`

**Comment by nalimilan** [comment]
When you say "if I do that", do you mean when you do either of the changes separately? Please be very specific. (The fact that calling `load` doesn't work is because the file doesn't contain correct data when you don't call `jldopen`.)

Could you add `@assert isfile(outfile)` before calling `jldopen`? Could you also show the full backtrace of the error you showed in the description (i.e. with line numbers)?

**Comment by kaarthiksundar** [comment]
I have a text file whose contents are as follows:

    numMachines 1
    timeSteps 720
    categoryOneCount 1
    categoryTwoPeriod 20
    seed 2002
    outfile m1.jld
    END

I read out line by line and create a variable in my program: `outfile = chomp(line[6][2])` 
Then, I run my algorithm and want to write its output to the `outfile` using the following code:

    file = "m1.jld"
    @assert outfile == file
    fid = jldopen(outfile, "w");
    write(fid, "TotalTime", totalWorkTime);
    close(fid);

The program throws an error for the above code. It also creates a file named "m1.jld\n" in the same folder. The error is as follows:

````
ERROR: LoadError: SystemError: opening file m1.jld: No such file or directory
 in open at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in open at iostream.jl:102
 in close at /Users/kaarthik/.julia/v0.4/JLD/src/JLD.jl:136
 in include at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in process_options at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/kaarthik/Dropbox/Sandia/Code/main1.jl, in expression starting on line 347
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: H5F.c line 301 in H5Fget_obj_count(): not a file id
    major: Invalid arguments to routine
    minor: Bad value
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
````

To fix this I changed the text file to

    numMachines 1
    timeSteps 720
    categoryOneCount 1
    categoryTwoPeriod 20
    seed 2002
    outfile m1.jld

All I do is remove the END line and the line break at the end of the last line. Then the code works fine and the output of the algorithm is written to the m1.jld file. I am able to retrieve the file contents.

**Comment by nalimilan** [comment]
Thanks, details are useful.

Still, does `@assert isfile(outfile)` fail?

**Comment by kaarthiksundar** [comment]
Sorry i missed that. Yes, `@assert misfile(outfile)` fails
````
 ERROR: LoadError: AssertionError: isfile(outfile)
 in include at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in process_options at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/kaarthik/Dropbox/Sandia/Code/main1.jl, in expression starting on line 343
````

**Comment by nalimilan** [comment]
OK, so doesn't look like it's an issue with JLD.jl, but with Julia. To be clear, this code fails only at the last assertion, right?
```julia
outfile = chomp(thisline[2]) # thisline[2] contains "m1.jld\n"
file = "m1.jld"
@assert outfile == file
@assert isfile(file)
@assert isfile(outfile)
```

If so, does this one also fail?
```julia
outfile = thisline[2][1:end-1]
file = "m1.jld"
@assert outfile == file
@assert isfile(file)
@assert isfile(outfile)
```

**Comment by simonster** [comment]
Closing since this seems like it is not a JLD bug
