### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION using @load

### ISSUE THREAD

**Issue by alix2m** [JuliaIO/JLD.jl#73]
Been mostly running Julia on a Mac. Switched to a more powerful (Windows) machine and while setting everything up and loading files with JLD received this error. Will attempt to debug myself, but submitting here just in case: 

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffaf5d00b7d -- RtlFreeHeap at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
RtlFreeHeap at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
RtlFreeHeap at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
free at C:\Windows\system32\msvcrt.dll (unknown line)
h5t_get_member_name at C:\Users\SERG\.julia\v0.4\HDF5\src\plain.jl:2167
jldatatype at C:\Users\SERG\.julia\v0.4\JLD\src\jld_types.jl:685
read at C:\Users\SERG\.julia\v0.4\JLD\src\JLD.jl:381
jl_apply_generic at C:\Users\SERG\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
read at C:\Users\SERG\.julia\v0.4\JLD\src\JLD.jl:357
anonymous at no file:0
jl_eval_with_compiler_p at C:\Users\SERG\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_parse_eval_all at C:\Users\SERG\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_load_file_string at C:\Users\SERG\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
include_string at C:\Users\SERG\.julia\v0.4\CodeTools\src\eval.jl:28
jlcall_include_string_1697 at  (unknown line)
jl_apply_generic at C:\Users\SERG\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at C:\Users\SERG\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Users\SERG\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Users\SERG\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_f_tuple at C:\Users\SERG\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
include_string at C:\Users\SERG\.julia\v0.4\CodeTools\src\eval.jl:32
jl_apply_generic at C:\Users\SERG\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
anonymous at C:\Users\SERG\.julia\v0.4\Atom\src\eval.jl:39
withpath at C:\Users\SERG\.julia\v0.4\Requires\src\require.jl:37
jl_apply_generic at C:\Users\SERG\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
withpath at C:\Users\SERG\.julia\v0.4\Atom\src\eval.jl:53
jl_apply_generic at C:\Users\SERG\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
anonymous at C:\Users\SERG\.julia\v0.4\Atom\src\eval.jl:61
jl_unprotect_stack at C:\Users\SERG\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)

**Comment by krcools** [comment]
I am running Julia 0.4.6 on Win10-64 and I get a similar error message. My test script is:

```
using JLD
using FixedSizeArrays
x = Vec(1,2,3)
@save "data.jld" x
@load "data.jld"
```

Depending on factors unbeknownst I either get

```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety).  Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x77aceef1 -- RtlAnsiStringToUnicodeString at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlAnsiStringToUnicodeString at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
free at C:\WINDOWS\system32\msvcrt.dll (unknown line)
h5t_get_member_name at C:\Users\ezzkc\.julia\v0.4\HDF5\src\plain.jl:2184
jldatatype at C:\Users\ezzkc\.julia\v0.4\JLD\src\jld_types.jl:687
read at C:\Users\ezzkc\.julia\v0.4\JLD\src\JLD.jl:390
jl_apply_generic at C:\Users\ezzkc\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
read at C:\Users\ezzkc\.julia\v0.4\JLD\src\JLD.jl:366
anonymous at no file:0
jl_eval_with_compiler_p at C:\Users\ezzkc\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_f_tuple at C:\Users\ezzkc\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
eval_user_input at REPL.jl:62
jlcall_eval_user_input_1295 at  (unknown line)
jl_apply_generic at C:\Users\ezzkc\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
anonymous at REPL.jl:92
jl_unprotect_stack at C:\Users\ezzkc\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
```

or 

```
ERROR: ReadOnlyMemoryError()
 in h5t_get_member_name at C:\Users\ezzkc\.julia\v0.4\HDF5\src\plain.jl:2184
 in jldatatype at C:\Users\ezzkc\.julia\v0.4\JLD\src\jld_types.jl:687
 in read at C:\Users\ezzkc\.julia\v0.4\JLD\src\JLD.jl:390
 in read at C:\Users\ezzkc\.julia\v0.4\JLD\src\JLD.jl:366
 in anonymous at no file
```

I even had this script complete successfully on rare occasions:

```julia
julia> using FixedSizeArrays
julia> using JLD
julia> x = Vec(1,2,3)
Vec(1,2,3)
julia> @save "data.jld" x
julia> @load "data.jld"
1-element Array{Symbol,1}:
 :x
julia> @load "data.jld"
1-element Array{Symbol,1}:
 :x
julia> x
Vec(1,2,3)
julia> exit()
```

Given that a `FixedSizeArrays.Vec` (@SimonDanisch)  is a wrapper around a `Tuple` I would not be surprised this is related to #12.

**Comment by krcools** [comment]
Actually the problem seems to occur with every user defined type. In addition JLD does not pass its tests on my configuration, neither on the release nor the master branch.

**Comment by krcools** [comment]
Package test of HDF5 fail in the same way. I will go bother them...

**Comment by timholy** [comment]
krcools, this works for me.
--Tim

**Comment by krcools** [comment]
I found the problem: HDF5.jl latches on to the Anaconda version of hdf5.dll, which as it turns out is not compatible: [HDF5.jl/#323](https://github.com/JuliaIO/HDF5.jl/issues/323).

**Comment by timholy** [comment]
Thanks, @krcools!

**Comment by timholy** [comment]
Closing this as redundant; @alix2m feel free to reopen if you disagree.

**Comment by alix2m** [comment]
Thanks @timholy and @krcools . Haven't had a chance to look into the solution proposed in HDF5.jl/#323 yet, but hopefully it'll solve the issue.  Will report back if issue persists.
