### ISSUE TITLE
Pre-compile failing

### ISSUE THREAD

**Issue by davidzentlermunro** [JuliaIO/JLD.jl#74]
When I run `using JLD` I get the following warnings:

`INFO: Recompiling stale cache file C:\Julia\PkgDir\lib\v0.4\JLD.ji for module JLD.
WARNING: Module HDF5 uuid did not match cache file
  This is likely because module HDF5 does not support  precompilation but is imported by a module that does.
WARNING: deserialization checks failed while attempting to load cache from C:\Julia\PkgDir\lib\v0.4\JLD.ji
INFO: Precompiling module JLD...
INFO: Recompiling stale cache file C:\Julia\PkgDir\lib\v0.4\JLD.ji for module JLD.
WARNING: Module HDF5 uuid did not match cache file
  This is likely because module HDF5 does not support  precompilation but is imported by a module that does.
__precompile__(true) but require failed to create a precompiled cache file`

If I then run say:
`A=ones(40)`
 `save("c:\\OneDrive\\Model\\myfile.jld", "A", A)`
I get the error: `UndefVarError: save not defined
 in include_string at loading.jl:288
 in eval at C:\Julia\PkgDir\v0.4\Atom\src\Atom.jl:3
 [inlined code] from C:\Julia\PkgDir\v0.4\Atom\src\eval.jl:39
 in anonymous at C:\Julia\PkgDir\v0.4\Atom\src\eval.jl:108
 in withpath at C:\Julia\PkgDir\v0.4\Requires\src\require.jl:37
 in withpath at C:\Julia\PkgDir\v0.4\Atom\src\eval.jl:53
 [inlined code] from C:\Julia\PkgDir\v0.4\Atom\src\eval.jl:107
 in anonymous at task.jl:58`

I'm using Atom 1.8.0 and Julia 0.4.7

**Comment by timholy** [comment]
Try quitting your julia session and starting a new one, and say `using JLD` as your first command. Does it fix the problem?

**Comment by davidzentlermunro** [comment]
Turns out it just needed a `Pkg.update()`. (http://stackoverflow.com/questions/37861746/julia-use-of-jld?noredirect=1#comment63186774_37861746) My bad...
