### ISSUE TITLE
Removal of UTF16String seems to have broken precompilation of JLD on v0.5

### ISSUE THREAD

**Issue by jrevels** [JuliaIO/JLD.jl#81]
ref @timholy [comment](https://github.com/JuliaCI/BaseBenchmarks.jl/pull/16#issuecomment-231823934). I didn't see an issue here for it, so I figured I should open one. 

(Thanks for pointing this out, Tim - I hadn't yet realized @nanosoldier had broken).

**Comment by timholy** [comment]
Closed by #82.
