### ISSUE TITLE
Running test failed

### ISSUE THREAD

**Issue by bravesalmon** [JuliaIO/JLD.jl#87]
Unable to run JLD test. Running Julia 0.4.6 64bit on Windows 10. When I tried test("JLD"), it failed with the following message. JLD version 0.6.0.

jldtests.jl
=================================[ ERROR: JLD ]=================================

failed process: Process(`'C:\Users\username\AppData\Local\Julia-0.4.6\bin\julia' --check-bounds=yes --code-coverage=none --color=no 'C:\Users\username\.julia\v0.4\JLD\test\runtests.jl'`, ProcessExited(3221226356)) [3221226356]
#

**Comment by bravesalmon** [comment]
FYI, full error message

jldtests.jl

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffb935ec41f -- RtlFreeHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlFreeHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlFreeHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
free at C:\WINDOWS\System32\msvcrt.dll (unknown line)
h5t_get_member_name at C:\Users\username\.julia\v0.4\HDF5\src\plain.jl:2184
jldatatype at C:\Users\username\.julia\v0.4\JLD\src\jld_types.jl:685
read at C:\Users\username\.julia\v0.4\JLD\src\JLD.jl:381
jl_apply_generic at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
read at C:\Users\username\.julia\v0.4\JLD\src\JLD.jl:357
jl_apply_generic at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
anonymous at C:\Users\username\.julia\v0.4\JLD\test\jldtests.jl:253
jl_eval_with_compiler_p at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_parse_eval_all at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_load_ at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
include at boot.jl:261
jl_apply_generic at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
include_from_node1 at loading.jl:320
jl_apply_generic at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
runtest at C:\Users\username\.julia\v0.4\JLD\test\runtests.jl:4
jl_apply_generic at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_parse_eval_all at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_load_ at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
include at boot.jl:261
jl_apply_generic at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
include_from_node1 at loading.jl:320
jl_apply_generic at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
process_options at client.jl:280
_start at client.jl:378
jlcall__start_511 at  (unknown line)
jl_apply_generic at C:\Users\username\AppData\Local\Julia-0.4.6\bin\libjulia.dll (unknown line)
unknown function (ip: 00000000004018D0)
unknown function (ip: 00000000004028AB)
unknown function (ip: 000000000040140C)
unknown function (ip: 000000000040153B)
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
=================================[ ERROR: JLD ]=================================

failed process: Process(`'C:\Users\username\AppData\Local\Julia-0.4.6\bin\julia' --check-bounds=yes --code-coverage=none --color=no 'C:\Users\username\.julia\v0.4\JLD\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================

**Comment by musm** [comment]
I think I might be getting the same error on rc3
```julia
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffa0b17c409 -- RtlFreeHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
while loading no file, in expression starting on line 0
RtlFreeHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlFreeHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
free at C:\WINDOWS\System32\msvcrt.dll (unknown line)
h5t_get_member_name at C:\Users\username\.julia\v0.5\HDF5\src\plain.jl:2184
jldatatype at C:\Users\username\.julia\v0.5\JLD\src\jld_types.jl:687
read at C:\Users\username\.julia\v0.5\JLD\src\JLD.jl:390
unknown function (ip: 00000000170F1A26)
read at C:\Users\username\.julia\v0.5\JLD\src\JLD.jl:366
unknown function (ip: 00000000170EED6A)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1930 #jldopen#9 at C:\Users\username\.julia\v0.5\JLD\src\JLD.jl:265
load at C:\Users\username\.julia\v0.5\JLD\src\JLD.jl:1226
unknown function (ip: 00000000170E7EBA)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1930 jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia.h:1392 [inlined]
jl_f__apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\builtins.c:533 #load#13 at C:\Users\username\.julia\v0.5\FileIO\src\loadsave.jl:45
load at C:\Users\username\.julia\v0.5\FileIO\src\loadsave.jl:45
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1930 do_call at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:66
eval at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:190
jl_toplevel_eval_flex at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:558 [inlined]
jl_toplevel_eval at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:580
jl_toplevel_eval_in_warn at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\builtins.c:576
eval at .\boot.jl:234
unknown function (ip: 0000000061C4F035)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1930 eval_user_input at .\REPL.jl:64
unknown function (ip: 00000000170C7FBA)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1930 macro expansion at .\REPL.jl:95 [inlined]
#3 at .\event.jl:68
unknown function (ip: 00000000170C12A3)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1930 jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia.h:1392 [inlined]
start_task at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:253
Allocations: 5625060 (Pool: 5623098; Big: 1962); GC: 9
```

**Comment by simonster** [comment]
Same as https://github.com/JuliaIO/HDF5.jl/issues/323

**Comment by bravesalmon** [comment]
JDL test passes (and JLD works well) if one uses older versions of packages. Below is a summary of package status on which JLD test passes.

7 required packages:
 - Atom                          0.4.2
 - Cairo                         0.2.32
 - DataFrames                    0.7.3
 - Distributions                 0.9.0
 - Gadfly                        0.4.2
 - HDF5                          0.6.2
 - JLD                           0.6.1
61 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.3.21
 - Blink                         0.3.4
 - Blosc                         0.1.5
 - Calculus                      0.1.15
 - CodeTools                     0.3.0
 - Codecs                        0.1.5
 - ColorTypes                    0.2.3
 - Colors                        0.6.4
 - Compat                        0.8.1
 - Compose                       0.4.2
 - Contour                       0.1.0
 - DataArrays                    0.3.3
 - DataStructures                0.4.4
 - Dates                         0.4.4
 - Distances                     0.3.1
 - Docile                        0.5.23
 - DualNumbers                   0.2.2
 - FactCheck                     0.4.3
 - FileIO                        0.1.0
 - FixedPointNumbers             0.1.3
 - FixedSizeArrays               0.2.1
 - GZip                          0.2.19
 - Graphics                      0.1.3
 - Grid                          0.4.0
 - Hexagons                      0.0.4
 - Hiccup                        0.0.2
 - HttpCommon                    0.2.6
 - HttpParser                    0.1.1
 - HttpServer                    0.1.5
 - Iterators                     0.1.9
 - JSON                          0.6.0
 - JuliaParser                   0.6.4
 - KernelDensity                 0.1.2
 - LNR                           0.0.2
 - Lazy                          0.10.1
 - LibExpat                      0.1.2
 - Loess                         0.0.6
 - MacroTools                    0.3.0
 - MbedTLS                       0.2.2
 - Measures                      0.0.2
 - Media                         0.1.2
 - Mustache                      0.0.15
 - Mux                           0.2.0
 - NaNMath                       0.2.1
 - Nettle                        0.2.3
 - Optim                         0.5.0
 - PDMats                        0.4.2
 - PositiveFactorizations        0.0.1
 - Reexport                      0.0.3
 - Requires                      0.2.2
 - SHA                           0.1.2
 - Showoff                       0.0.7
 - SortingAlgorithms             0.0.6
 - StatsBase                     0.8.2
 - StatsFuns                     0.2.2
 - URIParser                     0.1.3
 - WebSockets                    0.1.2
 - WinRPM                        0.1.15
 - WoodburyMatrices              0.1.5
 - Zlib                          0.1.12

**Comment by simonster** [comment]
Should be fixed by JuliaIO/HDF5.jl#333. Comment on JuliaIO/HDF5.jl#323 if not.
