### ISSUE TITLE
Custom types fail in Julia 0.5.0 on Windows

### ISSUE THREAD

**Issue by jpwspicer** [JuliaIO/JLD.jl#98]
The following code kills the Julia kernel:

``` julia
using JLD

type myType
    value::Float64
end

A = myType(rand())
jldopen("file.jld", "w") do file
    write(file, "A", A)
end

A = jldopen("file.jld", "r") do file
    read(file, "A")
end
```

I am using Julia 0.5.0 on Windows 10, with JLD v0.6.3 (same error occurs in v0.6.3+). I have reproduced this error on multiple Windows machines, but it does not occur in OSX.

Any advice would be appreciated, thanks!

**Comment by rand5** [comment]
+1 I'm also having this same problem

**Comment by greenflash1357** [comment]
I don't have the issue under Windows 10, Julia 0.5.0 and JLD v0.6.5.
Might be resolved in the latest release.

**Comment by jpwspicer** [comment]
I'm unclear how to update JLD to v0.6.5. Running `Pkg.checkout("JLD")` only upgrades it to v0.6.3+.

**Comment by greenflash1357** [comment]
Try `Pkg.update()`

**Comment by jpwspicer** [comment]
`Pkg.update()` updates JLD to v0.6.5+ (thanks for the tip!), however the original problem persists.

**Comment by greenflash1357** [comment]
What is your HDF5 version?

**Comment by jpwspicer** [comment]
v0.6.6

**Comment by TsurHerman** [comment]
+1

**Comment by simonster** [comment]
Probably the same issue as #103 but not possible to tell without a backtrace.

**Comment by jpwspicer** [comment]
Yes, updating to JLD v0.6.6 fixes the problem. Thanks!
